### ISSUE TITLE
React Consumer on Demo Server not working

### ISSUE THREAD

**Issue by sumps** [SignalK/react-consumer#3]
I am running the latest Chrome (Version 44.0.2403.155 m) on my Windows laptop and when I go to the Demo page of the new website and try to run the React Consumer, I just get a blank blue page....

![image](https://cloud.githubusercontent.com/assets/10165637/9359442/0c4364fe-4689-11e5-8216-00583f8c68f8.png)

If I run the JS console I get....

![image](https://cloud.githubusercontent.com/assets/10165637/9359498/4a55375e-4689-11e5-946f-b43627e8b3eb.png)

**Comment by timmathews** [comment]
Fixed. This demo will probably go away soon. Planning to move the unique widgets here to Instrument Panel.
